import os
import ycm_core
flags = [
        '-resource-dir',
        '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0',
        '-x objective-c',
        '-arch armv7',
        '-fmessage-length=0',
        # '-fmodules',
        # '-gmodules',
        '-fdiagnostics-show-note-include-stack',
        '-fmacro-backtrace-limit=0',
        '-D__arm__=1',
        '-D__IPHONE_OS_VERSION_MIN_REQUIRED=80000',
        '-std=gnu99',
        '-fobjc-arc',
        '-Wnon-modular-include-in-framework-module',
        '-Werror=non-modular-include-in-framework-module',
        '-Wno-trigraphs',
        '-fpascal-strings',
        '-Os',
        '-fno-common',
        '-Wno-missing-field-initializers',
        '-Wno-missing-prototypes',
        '-Werror=return-type',
        '-Wunreachable-code',
        '-Wno-implicit-atomic-properties',
        '-Werror=deprecated-objc-isa-usage',
        '-Werror=objc-root-class',
        '-Wno-arc-repeated-use-of-weak',
        '-Wduplicate-method-match',
        '-Wno-missing-braces',
        '-Wparentheses',
        '-Wswitch',
        '-Wunused-function',
        '-Wno-unused-label',
        '-Wno-unused-parameter',
        '-Wunused-variable',
        '-Wunused-value',
        '-Wempty-body',
        '-Wconditional-uninitialized',
        '-Wno-unknown-pragmas',
        '-Wno-shadow',
        '-Wno-four-char-constants',
        '-Wno-conversion',
        '-Wconstant-conversion',
        '-Wint-conversion',
        '-Wbool-conversion',
        '-Wenum-conversion',
        '-Wshorten-64-to-32',
        '-Wpointer-sign',
        '-Wno-newline-eof',
        '-Wno-selector',
        '-Wno-strict-selector-match',
        '-Wundeclared-selector',
        '-Wno-deprecated-implementations',
        '-DOBJC_OLD_DISPATCH_PROTOTYPES=0',
        '-isysroot',
        '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk',
        '-fstrict-aliasing',
        '-Wprotocol',
        '-Wdeprecated-declarations',
        '-miphoneos-version-min=8.0',
        '-g',
        '-Wno-sign-conversion',
        '-Wno-infinite-recursion',
        '-fembed-bitcode-marker',
        '-I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform',
        '-I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include',
        '-I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks',
        '-I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0/include',
        '-F/Users/apple/Documents/Developer/CloudLifeWorkspace/iOS/Develop/Project_iOS/project',
        '-MMD',
        '-MT',
        '-MF',
]
SOURCE_EXTENSIONS = [ '.cpp', '.cxx', '.cc', '.c', '.m', '.mm' ]
HEADER_EXTENSIONS = [ '.hpp', '.hxx', '.hh', '.h' ]
def FlagsForFile( filename, **kwargs ):
        staticFlags = flags
        return {
                'flags': staticFlags,
                'do_cache': True
        }
